/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psptarea4;
import java.util.List;
import tarea6.WebServiceT6; 
import tarea6.WebServiceT6_Service;
import tarea6.Pais; 
import tarea6.Moneda; 
import tarea6.Zona;  
/**
 *
 * @author navag
 */
public class FrameTarea extends javax.swing.JFrame {

    /**
     * Creates new form FrameTarea
     */
    WebServiceT6_Service s = new WebServiceT6_Service(); 
    WebServiceT6 conexion = s.getWebServiceT6Port(); 
 
    List<Zona> zonas = conexion.getZonas(); 
    
    public FrameTarea() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgeo = new javax.swing.JButton();
        btmonedas = new javax.swing.JButton();
        btpaises = new javax.swing.JButton();
        btBuscarzona = new javax.swing.JButton();
        btBuscarMoneda = new javax.swing.JButton();
        jMoneda = new javax.swing.JTextField();
        btBuscarPais = new javax.swing.JButton();
        jPais = new javax.swing.JTextField();
        jZona = new javax.swing.JTextField();
        jTextarea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btgeo.setText("Listado de zonas geográficas");
        btgeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgeoActionPerformed(evt);
            }
        });

        btmonedas.setText("Listado de monedas");
        btmonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmonedasActionPerformed(evt);
            }
        });

        btpaises.setText("Listado de paises");
        btpaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpaisesActionPerformed(evt);
            }
        });

        btBuscarzona.setText("Paises por zona");
        btBuscarzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarzonaActionPerformed(evt);
            }
        });

        btBuscarMoneda.setText("Listado de países por moneda");
        btBuscarMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarMonedaActionPerformed(evt);
            }
        });

        jMoneda.setText("(EUR,USD...)");

        btBuscarPais.setText("Buscar por pais");
        btBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPaisActionPerformed(evt);
            }
        });

        jPais.setText("(España,Alemania...)");
        jPais.setToolTipText("");

        jZona.setText("(Africa,Europa....)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("******************************************************** * \n PSP - Tarea Individual 4 - Web Services      \n * ******************************************************** * \n IGNACIO VALERO GARCIA                 \n * ******************************************************** * \n 14630673M                                          \n  * ******************************************************** ");
        jTextarea.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscarMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMoneda)
                    .addComponent(jPais)
                    .addComponent(jZona)
                    .addComponent(btBuscarzona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btpaises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btmonedas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btgeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscarPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextarea, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btgeo)
                        .addGap(26, 26, 26)
                        .addComponent(btmonedas)
                        .addGap(18, 18, 18)
                        .addComponent(btpaises)
                        .addGap(37, 37, 37)
                        .addComponent(btBuscarzona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btBuscarMoneda)
                        .addGap(18, 18, 18)
                        .addComponent(jMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarPais)
                        .addGap(18, 18, 18)
                        .addComponent(jPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btgeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgeoActionPerformed
       jTextArea1.setText("");
        for(int i =0; i< zonas.size();i++)
       {
           
            jTextArea1.append(zonas.get(i).getNombre()+"\n");
       }
       
    }//GEN-LAST:event_btgeoActionPerformed

    private void btmonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmonedasActionPerformed
        jTextArea1.setText(""); 
        for(int i =0; i< conexion.getMonedas().size();i++)
       {
            
            jTextArea1.append(conexion.getMonedas().get(i).getCodigo()+": ");
            jTextArea1.append(conexion.getMonedas().get(i).getNombre()+"\n");
            
       }
    }//GEN-LAST:event_btmonedasActionPerformed

    private void btpaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpaisesActionPerformed
        // TODO add your handling code here:
           jTextArea1.setText(""); 
        for(int i =0; i< conexion.getPaises().size();i++)
       {
            
            
            jTextArea1.append(conexion.getPaises().get(i).getNombre()+"\n");
            
       }
    }//GEN-LAST:event_btpaisesActionPerformed

    private void btBuscarzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarzonaActionPerformed
       
           jTextArea1.setText("");
           //nombre zona  jZona.getText();
           int numeroZona=0;
              for(int i =0; i< zonas.size();i++)
       {
           if(zonas.get(i).getNombre().compareToIgnoreCase(jZona.getText())==0)
               numeroZona = (int) zonas.get(i).getId();
           
            
       }
              if(numeroZona==0)
                jTextArea1.append("No se encuentra zona \n ejemplo: Africa , Europa...");
        for(int i =0; i< conexion.getPaises().size();i++)
       {
           if(conexion.getPaises().get(i).getIdArea() == numeroZona)
            jTextArea1.append( conexion.getPaises().get(i).getNombre()+"\n");
       }
    }//GEN-LAST:event_btBuscarzonaActionPerformed

    private void btBuscarMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarMonedaActionPerformed
        // TODO add your handling code here:
         jTextArea1.setText("");
         for(int i =0; i< conexion.getPaisesMoneda(jMoneda.getText()).size();i++)
       {
           
            jTextArea1.append( conexion.getPaisesMoneda(jMoneda.getText()).get(i).getNombre()+"\n");
       }
    }//GEN-LAST:event_btBuscarMonedaActionPerformed

    private void btBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPaisActionPerformed
        // TODO add your handling code here:
          jTextArea1.setText("");
           
         for(int i =0; i< conexion.getPaises().size();i++)
       {
            if(conexion.getPaises().get(i).getNombre().compareToIgnoreCase(jPais.getText())==0)
            jTextArea1.append("CODIGO: "+  conexion.getPaises().get(i).getId()+"\n"+
                                "NOMBRE: "+conexion.getPaises().get(i).getNombre()+"\n"+
                                "BANDERA: "+conexion.getPaises().get(i).getCodigoBandera()+"\n"+
                                          "DIVISA: "+ conexion.getPaises().get(i).getCodigoDivisa()+"\n"+
                                                 "NIC: "+  conexion.getPaises().get(i).getCodigoNic()+"\n"+
                                                     "AREA: "+   conexion.getPaises().get(i).getIdArea()+"\n");
       }
    }//GEN-LAST:event_btBuscarPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarMoneda;
    private javax.swing.JButton btBuscarPais;
    private javax.swing.JButton btBuscarzona;
    private javax.swing.JButton btgeo;
    private javax.swing.JButton btmonedas;
    private javax.swing.JButton btpaises;
    private javax.swing.JTextField jMoneda;
    private javax.swing.JTextField jPais;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane jTextarea;
    private javax.swing.JTextField jZona;
    // End of variables declaration//GEN-END:variables
}
